### ISSUE TITLE
windfind like listary?

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindFind#1]
...

**Comment by gooker** [comment]
Finally seeing you online, looking forward to the new version

**Comment by kingToolbox** [comment]
I'm really glad to see you again! It's hard to believe it's been three weeks already. I've been out a lot lately, so I haven't had much time to get online.

I just wrapped up and released [WindFind Birth](https://github.com/kingToolbox/WindFind/releases/tag/1.0.0), so if you’re interested, feel free to check it out. The Linux and macOS versions are coming out later this month. I’m also hoping to get `WindTerm 2.7.0` out this month; it’s mostly done, but I still need to finish some features and do some testing. The new version has some cool stuff, like [tmux-integration](https://iterm2.com/documentation-tmux-integration.html). I just wish I had more time to work on it!
